import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Section order comes from the _category_.json positions. Deprecated pages
// (e.g. legacy wallet-cli command names) are filtered out of the sidebar by
// the sidebarItemsGenerator configured in docusaurus.config.ts.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
